spring:
  application:
    name: yhkim-eureka-client-a
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}