server:
  port: 8888
spring:
  profiles:
    active: prod
  application:
    name: config
  cloud:
    config:
      server:
        git:
          # git address
          uri: https://github.com/kimyounghoi/study-spring-cloud
          # git config files path
          search-paths: spring-cloud-config/test-cloud-config-files/**
          # git branch name
          default-label: main